"""Read and write Mod Organizer 2 profile files (modlist.txt, plugins.txt, meta.ini).

讀寫 MO2 設定檔：modlist.txt、plugins.txt、loadorder.txt 與 mod 的 meta.ini。

File conventions (verified against MO2 source, profile.cpp):
- modlist.txt: first line = HIGHEST priority. '+' enabled, '-' disabled,
  '*' unmanaged/foreign (DLC, Creation Club). Separators are mods whose folder
  name ends with '_separator'. Lines whose folder is missing on disk are
  silently DROPPED by MO2 on load and the file is rewritten.
- plugins.txt: one plugin per line, '*' prefix = enabled; order = load order.
- loadorder.txt: optional; when present it wins over plugins.txt at startup.
"""

from __future__ import annotations

import configparser
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

SEPARATOR_SUFFIX = "_separator"
MO2_HEADER = "# This file was automatically generated by Mod Organizer."


@dataclass(frozen=True)
class ModEntry:
    name: str
    state: str  # '+', '-' or '*'
    line_no: int = 0  # 1-based line number in the source file (0 = synthetic)

    @property
    def enabled(self) -> bool:
        return self.state == "+"

    @property
    def is_separator(self) -> bool:
        return self.name.endswith(SEPARATOR_SUFFIX)

    @property
    def is_foreign(self) -> bool:
        return self.state == "*"

    def line(self) -> str:
        return f"{self.state}{self.name}"


@dataclass(frozen=True)
class PluginEntry:
    name: str
    enabled: bool
    line_no: int = 0

    def line(self) -> str:
        return ("*" if self.enabled else "") + self.name


def _read_lines(path: Path) -> list[str]:
    raw = Path(path).read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        raw = raw[3:]
    text = raw.decode("utf-8", errors="replace")
    return text.splitlines()


def read_modlist(path: Path) -> list[ModEntry]:
    """Parse modlist.txt keeping file order (first = highest priority)."""
    entries: list[ModEntry] = []
    for i, line in enumerate(_read_lines(path), start=1):
        if not line.strip() or line.startswith("#"):
            continue
        state, name = line[0], line[1:]
        if state not in "+-*":
            # MO2 treats a bare name as enabled; keep it but flag the state.
            state, name = "+", line
        entries.append(ModEntry(name=name, state=state, line_no=i))
    return entries


def write_modlist(path: Path, entries: Iterable[ModEntry], newline: str = "\r\n") -> None:
    lines = [MO2_HEADER] + [e.line() for e in entries]
    Path(path).write_text(newline.join(lines) + newline, encoding="utf-8", newline="")


def read_plugins(path: Path) -> list[PluginEntry]:
    """Parse plugins.txt or loadorder.txt (no '*' in loadorder.txt means 'listed')."""
    out: list[PluginEntry] = []
    for i, line in enumerate(_read_lines(path), start=1):
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("*"):
            out.append(PluginEntry(s[1:], True, i))
        else:
            out.append(PluginEntry(s, False, i))
    return out


def write_plugins(path: Path, entries: Iterable[PluginEntry], newline: str = "\r\n") -> None:
    lines = ["# This file was automatically generated by Mod Organizer."] + [e.line() for e in entries]
    Path(path).write_text(newline.join(lines) + newline, encoding="utf-8", newline="")


def enabled_mods(entries: Iterable[ModEntry]) -> list[ModEntry]:
    return [e for e in entries if e.enabled and not e.is_separator]


def fold(name: str) -> str:
    """Case-insensitive comparison key (Windows file names are case-insensitive)."""
    return name.casefold().strip()


_DUP_SUFFIX = re.compile(r"^(?P<base>.*?\D)(?P<num>[2-9]|[1-9]\d)$")


def strip_dup_suffix(name: str) -> str | None:
    """Return the name without an MO2 duplicate-install digit suffix, or None.

    When MO2 installs an archive into an existing folder name the user can pick
    "rename", which appends a number (e.g. 'Wyrmstooth2', 'Lux - Via (patch hub)2').
    Names that legitimately end with a number ('Paper Map 2') cannot be told
    apart from text alone, so callers must treat the result as a *candidate*.
    """
    m = _DUP_SUFFIX.match(name)
    if not m:
        return None
    base = m.group("base").rstrip()
    return base or None


@dataclass
class ModMeta:
    folder: str
    game_name: str = ""
    mod_id: int = 0
    file_id: int = 0
    version: str = ""
    installation_file: str = ""
    repository: str = ""
    url: str = ""
    raw: dict | None = None


def read_meta_ini(path: Path) -> ModMeta:
    """Read an MO2 meta.ini (tolerant of duplicate keys and odd encodings)."""
    path = Path(path)
    cp = configparser.RawConfigParser(strict=False, interpolation=None)
    cp.optionxform = str  # keep key case
    text = path.read_bytes().decode("utf-8", errors="replace")
    try:
        cp.read_string(text)
    except configparser.Error:
        cp.read_string("[General]\n" + text)
    general = dict(cp.items("General")) if cp.has_section("General") else {}

    def as_int(v: str | None) -> int:
        try:
            return int(str(v).strip().strip('"'))
        except (TypeError, ValueError):
            return 0

    file_id = 0
    if cp.has_section("installedFiles"):
        for k, v in cp.items("installedFiles"):
            if k.endswith("fileid"):
                file_id = as_int(v)
                break
    return ModMeta(
        folder=path.parent.name,
        game_name=general.get("gameName", "").strip(),
        mod_id=as_int(general.get("modid")),
        file_id=file_id,
        version=general.get("version", "").strip(),
        installation_file=general.get("installationFile", "").strip(),
        repository=general.get("repository", "").strip(),
        url=general.get("url", "").strip(),
        raw={s: dict(cp.items(s)) for s in cp.sections()},
    )


def _ini_value(value: str) -> str:
    """Quote a value the way QSettings needs: list/comment characters, or a leading '@'
    (QSettings reads '@ByteArray(...)', '@Variant(...)' as typed values)."""
    if value == value.strip() and not value.startswith("@") and not any(c in value for c in ',;#"\\'):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def install_meta_text(mod_id: str, file_id: str, version: str, installation_file: str) -> str:
    """meta.ini for a mod installed from a Nexus download (what MO2 writes, minus UI state)."""
    lines = ["[General]", "gameName=skyrimse", f"modid={mod_id}", f"version={_ini_value(version)}",
             f"installationFile={_ini_value(installation_file)}", "repository=Nexus", "",
             "[installedFiles]", f"1\\modid={mod_id}", f"1\\fileid={file_id}", "size=1"]
    return "\r\n".join(lines) + "\r\n"


def mark_download_installed(text: str) -> str:
    """Return a download .meta text with installed=true / uninstalled=false in [General].

    Blank lines are dropped, which also repairs the doubled CR line ends ("\\r\\r\\n") that
    older nexus_fetch versions wrote.
    """
    wanted = {"installed": "true", "uninstalled": "false"}
    out: list[str] = []
    seen: set[str] = set()
    in_general = found_general = False

    def add_missing() -> None:
        out.extend(f"{k}={v}" for k, v in wanted.items() if k not in seen)
        seen.update(wanted)

    for line in (ln for ln in text.splitlines() if ln.strip()):
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            if in_general:
                add_missing()
            in_general = s.lower() == "[general]"
            found_general = found_general or in_general
            out.append(line)
            continue
        key = s.partition("=")[0].strip().lower()
        if in_general and key in wanted:
            if key not in seen:
                out.append(f"{key}={wanted[key]}")
                seen.add(key)
            continue
        out.append(line)
    if in_general:
        add_missing()
    if not found_general:
        out = ["[General]"] + [f"{k}={v}" for k, v in wanted.items()] + out
    return "\r\n".join(out) + "\r\n"


def nexus_url(mod_id: int, file_id: int = 0, game: str = "skyrimspecialedition") -> str:
    if not mod_id:
        return ""
    base = f"https://www.nexusmods.com/{game}/mods/{mod_id}"
    return f"{base}?tab=files&file_id={file_id}" if file_id else base


def find_instance_paths(instance_dir: Path) -> dict[str, Path]:
    """Locate mods/profiles/downloads/overwrite for an MO2 instance.

    Honors ModOrganizer.ini [Settings] overrides (base_directory, mod_directory, ...)
    and falls back to the standard portable layout.
    """
    instance_dir = Path(instance_dir)
    paths = {
        "base": instance_dir,
        "mods": instance_dir / "mods",
        "profiles": instance_dir / "profiles",
        "downloads": instance_dir / "downloads",
        "overwrite": instance_dir / "overwrite",
    }
    ini = instance_dir / "ModOrganizer.ini"
    if ini.exists():
        cp = configparser.RawConfigParser(strict=False, interpolation=None)
        cp.optionxform = str
        try:
            cp.read_string(ini.read_bytes().decode("utf-8", errors="replace"))
        except configparser.Error:
            return paths
        if cp.has_section("Settings"):
            s = dict(cp.items("Settings"))
            base = _ini_path(s.get("base_directory")) or instance_dir
            if not base.is_absolute():
                base = instance_dir / base
            paths["base"] = base
            for key, ini_key in (("mods", "mod_directory"), ("profiles", "profiles_directory"),
                                 ("downloads", "download_directory"), ("overwrite", "overwrite_directory")):
                val = _ini_path(s.get(ini_key))
                if val:
                    val = Path(str(val).replace("%BASE_DIR%", str(base)))
                    paths[key] = val if val.is_absolute() else base / val
                else:
                    paths[key] = base / paths[key].name
        if cp.has_section("General"):
            gp = _ini_path(dict(cp.items("General")).get("gamePath"))
            if gp:
                paths["game"] = gp
    return paths


def locate_instance(root: Path) -> dict[str, Path]:
    """Find the MO2 folders for a Nolvus, Wabbajack or plain portable install.

    Nolvus:     <Inst>\\MO2\\ModOrganizer.ini, <Inst>\\MODS\\{mods,profiles,...}, <Inst>\\STOCK GAME
    Wabbajack:  <Inst>\\ModOrganizer.ini, <Inst>\\{mods,profiles,...}, <Inst>\\Stock Game
    """
    root = Path(root)
    ini_dir = root
    for cand in (root, root / "MO2"):
        if (cand / "ModOrganizer.ini").exists():
            ini_dir = cand
            break
    paths = find_instance_paths(ini_dir)
    if not paths["mods"].is_dir():
        for cand in (root / "MODS", root / "mods", ini_dir.parent / "MODS"):
            base = cand if cand.name.upper() == "MODS" else cand.parent
            if (base / "mods").is_dir():
                for k in ("mods", "profiles", "downloads", "overwrite"):
                    paths[k] = base / k
                break
    if "game" not in paths or not Path(paths["game"]).exists():
        for name in ("STOCK GAME", "Stock Game", "Game Root"):
            for base in (root, ini_dir, ini_dir.parent):
                if (base / name / "SkyrimSE.exe").exists():
                    paths["game"] = base / name
                    break
            if "game" in paths and Path(paths["game"]).exists():
                break
    paths["ini_dir"] = ini_dir
    return paths


def list_profiles(profiles_dir: Path) -> list[str]:
    p = Path(profiles_dir)
    return sorted(d.name for d in p.iterdir() if (d / "modlist.txt").exists()) if p.is_dir() else []


def _ini_path(value: str | None) -> Path | None:
    if not value:
        return None
    v = value.strip()
    m = re.match(r'^@ByteArray\((.*)\)$', v)
    if m:
        v = m.group(1)
    v = v.strip('"').replace("\\\\", "\\")
    return Path(v) if v else None


def qt_bytearray(value: str) -> str:
    """Encode a path the way MO2 writes it: @ByteArray(D:\\\\PM\\\\STOCK GAME)."""
    return "@ByteArray(" + value.replace("\\", "\\\\") + ")"
